export const chatbot = [
  {
    keywords: {
      en: ["client", "download", "launcher"],
      es: ["descargar", "descarga", "cliente", "launcher"],
      et: ["alla", "laadi", "klient", "launcher"],
      lv: ["lejupielāde", "lejupielādēt", "klients", "launcher"],
      pl: ["pobierz", "pobieranie", "klient", "launcher"],
      pt: ["baixar", "download", "cliente", "launcher"],
      ru: ["скачать", "загрузка", "клиент", "лаунчер"],
      tr: ["indir", "indirme", "istemci", "launcher"],
      vi: ["tải", "tải về", "client", "launcher"],
    },
    answerKey: "chatbot.download",
    links: [{ labelKey: "chatbot.links.download", to: "/downloads" }],
  },

  {
    keywords: {
      en: [
        "event",
        "events",
        "invasion",
        "blood castle",
        "bloodcastle",
        "devil square",
        "devilsquare",
        "red dragon",
        "chaos castle",
        "crywolf",
        "castle siege",
        "golden dragon",
        "golden invasion",
        "illusion temple",
        "arka war",
      ],
      es: [
        "evento",
        "eventos",
        "invasión",
        "blood castle",
        "devil square",
        "dragón rojo",
        "asedio",
        "crywolf",
      ],
      et: [
        "event",
        "sündmus",
        "sündmused",
        "invasioon",
        "blood castle",
        "devil square",
      ],
      lv: ["pasākums", "pasākumi", "iebrukums", "blood castle", "devil square"],
      pl: [
        "event",
        "eventy",
        "inwazja",
        "blood castle",
        "devil square",
        "oblężenie",
      ],
      pt: ["evento", "eventos", "invasão", "blood castle", "devil square"],
      ru: [
        "ивент",
        "ивенты",
        "событие",
        "события",
        "вторжение",
        "blood castle",
        "devil square",
        "осада",
      ],
      tr: [
        "etkinlik",
        "etkinlikler",
        "istila",
        "blood castle",
        "devil square",
        "kuşatma",
      ],
      vi: ["sự kiện", "event", "xâm lược", "blood castle", "devil square"],
    },
    answerKey: "chatbot.events",
    links: [{ labelKey: "chatbot.links.events", to: "/events" }],
  },

  {
    keywords: {
      en: ["reset", "resets", "max reset", "how to reset"],
      es: ["reset", "reinicio", "reinicios", "cómo resetear", "resetear"],
      et: ["reset", "resett", "kuidas reset"],
      lv: ["reset", "reseti", "kā resetot"],
      pl: ["reset", "resetować", "jak zresetować", "resetów"],
      pt: ["reset", "resetar", "como resetar"],
      ru: ["ресет", "сброс", "как ресет", "как сбросить"],
      tr: ["reset", "nasıl reset", "reset at"],
      vi: ["reset", "làm reset", "reset như thế nào"],
    },
    answerKey: "chatbot.reset",
  },

  {
    keywords: {
      en: ["grand reset", "grandreset", "gr", "grand reset reward"],
      es: ["grand reset", "grandreset", "recompensa grand reset"],
      et: ["grand reset", "grandreset", "gr"],
      lv: ["grand reset", "grandreset", "gr"],
      pl: ["grand reset", "grandreset", "nagroda grand reset"],
      pt: ["grand reset", "grandreset", "recompensa grand reset"],
      ru: ["гранд ресет", "grand reset", "награда гранд ресет"],
      tr: ["grand reset", "grandreset", "grand reset ödül"],
      vi: ["grand reset", "phần thưởng grand reset"],
    },
    answerKey: "chatbot.grandReset",
  },

  {
    keywords: {
      en: ["max stat", "stats", "max stats", "maximum stats"],
      es: ["stats", "estadísticas", "máximo stat", "máximas estadísticas"],
      et: ["stat", "stats", "max stat"],
      lv: ["stati", "max stat", "maksimālie stati"],
      pl: ["staty", "max stat", "maksymalne staty"],
      pt: ["status", "stats", "max stats", "máximo"],
      ru: ["статы", "макс статы", "максимум статов"],
      tr: ["stat", "max stat", "maks stat"],
      vi: ["chỉ số", "max stat", "tối đa"],
    },
    answerKey: "chatbot.maxStats",
  },

  {
    keywords: {
      en: ["quest", "/evo", "evo", "evolution", "class", "class change"],
      es: [
        "misión",
        "misiones",
        "evo",
        "evolución",
        "clase",
        "cambio de clase",
      ],
      et: ["quest", "evo", "evolutsioon", "klass"],
      lv: ["quest", "uzdevums", "evo", "evolūcija", "klase"],
      pl: ["quest", "zadanie", "ewolucja", "klasa", "zmiana klasy"],
      pt: ["missão", "quest", "evo", "evolução", "classe"],
      ru: ["квест", "эволюция", "класс", "смена класса"],
      tr: ["görev", "quest", "evrim", "sınıf", "sınıf değişimi"],
      vi: ["nhiệm vụ", "quest", "evo", "tiến hóa", "đổi lớp"],
    },
    answerKey: "chatbot.evolution",
  },

  {
    keywords: {
      en: ["barracks", "crywolf", "3rd", "3rd class"],
      es: ["barracks", "crywolf", "3ra", "3ª clase", "tercera clase"],
      et: ["barracks", "crywolf", "3. klass"],
      lv: ["barracks", "crywolf", "3. klase"],
      pl: ["barracks", "crywolf", "3 klasa", "trzecia klasa"],
      pt: ["barracks", "crywolf", "3ª classe"],
      ru: ["бараки", "barracks", "crywolf", "3 класс"],
      tr: ["barracks", "crywolf", "3. sınıf"],
      vi: ["barracks", "crywolf", "lớp 3"],
    },
    answerKey: "chatbot.barracks",
  },

  {
    keywords: {
      en: ["commands", "command"],
      es: ["comandos", "comando"],
      et: ["käsk", "käsud", "commands"],
      lv: ["komandas", "komanda"],
      pl: ["komendy", "komenda"],
      pt: ["comandos", "comando"],
      ru: ["команды", "команда"],
      tr: ["komutlar", "komut"],
      vi: ["lệnh", "các lệnh"],
    },
    answerKey: "chatbot.commands",
    links: [{ labelKey: "chatbot.links.guides", to: "/info" }],
  },

  {
    keywords: {
      en: ["season", "files", "season info", "which season"],
      es: ["temporada", "season", "qué temporada", "info temporada"],
      et: ["season", "hooaeg", "mis season"],
      lv: ["sezona", "season", "kura sezona"],
      pl: ["sezon", "season", "jaki sezon"],
      pt: ["temporada", "season", "qual temporada"],
      ru: ["сезон", "какой сезон", "season"],
      tr: ["sezon", "hangi sezon", "season"],
      vi: ["season", "mùa", "phiên bản", "season mấy"],
    },
    answerKey: "chatbot.season",
  },

  {
    keywords: {
      en: ["font issue", "squares", "weird text", "text issue", "font", "text"],
      es: ["fuente", "cuadrados", "texto raro", "problema de texto"],
      et: ["font", "ruudud", "tekst", "teksti probleem"],
      lv: ["fonts", "kvadrāti", "teksts", "teksta problēma"],
      pl: ["czcionka", "kwadraty", "tekst", "problem z tekstem"],
      pt: ["fonte", "quadrados", "texto estranho", "problema de texto"],
      ru: ["шрифт", "квадраты", "текст", "проблема текста"],
      tr: ["font", "kareler", "yazı", "metin sorunu"],
      vi: ["font", "ô vuông", "lỗi chữ", "chữ bị lỗi"],
    },
    answerKey: "chatbot.font",
    links: [{ labelKey: "chatbot.links.download", to: "/downloads" }],
  },

  {
    keywords: {
      en: [
        "drop",
        "drops",
        "item",
        "armor",
        "weapon",
        "where to farm",
        "farm items",
        "farm",
      ],
      es: [
        "drop",
        "objetos",
        "ítem",
        "arma",
        "armadura",
        "farmear",
        "dónde farmear",
      ],
      et: ["drop", "esemed", "item", "relv", "rüü", "farm"],
      lv: ["drop", "item", "ieroči", "bruņas", "farmot", "kur farmot"],
      pl: [
        "drop",
        "item",
        "przedmiot",
        "broń",
        "zbroja",
        "farmić",
        "gdzie farmić",
      ],
      pt: [
        "drop",
        "itens",
        "item",
        "arma",
        "armadura",
        "farmar",
        "onde farmar",
      ],
      ru: ["дроп", "предмет", "вещи", "броня", "оружие", "где фармить", "фарм"],
      tr: ["drop", "eşya", "item", "silah", "zırh", "farm", "nerede farm"],
      vi: ["drop", "vật phẩm", "item", "vũ khí", "giáp", "farm", "farm ở đâu"],
    },
    answerKey: "chatbot.drops",
    links: [{ labelKey: "chatbot.links.guides", to: "/info" }],
  },
];
